//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsbEnabler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>c:\temp</string>
  <string>d:\temp</string>
  <string>d:\dump</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ParseDirs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ParseDirs"]));
            }
            set {
                this["ParseDirs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>$Recycle.Bin</string>
  <string>boot</string>
  <string>bPowerTemp</string>
  <string>config.Msi</string>
  <string>Documents and Settings</string>
  <string>MSOCache</string>
  <string>PerfLogs</string>
  <string>Program Files</string>
  <string>Program Files (x86)</string>
  <string>ProgramData</string>
  <string>Recovery</string>
  <string>System Volume Information</string>
  <string>Windows</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SkipDirs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SkipDirs"]));
            }
            set {
                this["SkipDirs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowUI {
            get {
                return ((bool)(this["ShowUI"]));
            }
            set {
                this["ShowUI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\store")]
        public string StorePath {
            get {
                return ((string)(this["StorePath"]));
            }
            set {
                this["StorePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jpg,jpeg,png")]
        public string FileExtList {
            get {
                return ((string)(this["FileExtList"]));
            }
            set {
                this["FileExtList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~temp12.log")]
        public string LogFile {
            get {
                return ((string)(this["LogFile"]));
            }
            set {
                this["LogFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScanAllDirs {
            get {
                return ((bool)(this["ScanAllDirs"]));
            }
            set {
                this["ScanAllDirs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScanOnly {
            get {
                return ((bool)(this["ScanOnly"]));
            }
            set {
                this["ScanOnly"] = value;
            }
        }
    }
}
