//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OliverBlogCruz.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("js")]
        public string FileExtExpressionJS {
            get {
                return ((string)(this["FileExtExpressionJS"]));
            }
            set {
                this["FileExtExpressionJS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("html,htm,php,asp,aspx,mspx")]
        public string FileExtExpressionWebPage {
            get {
                return ((string)(this["FileExtExpressionWebPage"]));
            }
            set {
                this["FileExtExpressionWebPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jpeg,jpg,jpe,gif,bmp,png,tiff")]
        public string FileExtExpressionImage {
            get {
                return ((string)(this["FileExtExpressionImage"]));
            }
            set {
                this["FileExtExpressionImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("css")]
        public string FileExtExpressionStyle {
            get {
                return ((string)(this["FileExtExpressionStyle"]));
            }
            set {
                this["FileExtExpressionStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\temp\\test\\")]
        public string StoreBasePath {
            get {
                return ((string)(this["StoreBasePath"]));
            }
            set {
                this["StoreBasePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test User Agent")]
        public string UserAgent {
            get {
                return ((string)(this["UserAgent"]));
            }
            set {
                this["UserAgent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB.1;User Id=sa;Password=openopen;Initial Catalog=BizGenX;Data Sou" +
            "rce=.;")]
        public string DBConnection {
            get {
                return ((string)(this["DBConnection"]));
            }
            set {
                this["DBConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"pzy.be,photoshare,hubimg,postimage,imagebam,idlebrain,hqimage,desiupload,cinesnacks,cineindya,cinefun,cinegoer,tamilsguide,bollywoodmantra,tamilmax,sulekha,uploadhouse,imagerevenue,ragalahari,photobucket,indiaglitz,sphotos,imgbox,postimage,piczclub,indiaglitz,sphotos,imgbox,postimage,piczclub,pixslam,imagebam,yoopic,imagehost,imageshack")]
        public string FiltersInclude {
            get {
                return ((string)(this["FiltersInclude"]));
            }
            set {
                this["FiltersInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FiltersExclude {
            get {
                return ((string)(this["FiltersExclude"]));
            }
            set {
                this["FiltersExclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.exbii.com/showthread.php?t=abc&page=[i]")]
        public string UrlPattern {
            get {
                return ((string)(this["UrlPattern"]));
            }
            set {
                this["UrlPattern"] = value;
            }
        }
    }
}
