#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oliva.GenX.DataTier
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BizGenX")]
	public partial class GenXModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGrabList(GrabList instance);
    partial void UpdateGrabList(GrabList instance);
    partial void DeleteGrabList(GrabList instance);
    #endregion
		
		public GenXModelDataContext() : 
				base(global::Oliva.GenX.DataTier.Properties.Settings.Default.BizGenXConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GenXModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GenXModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GenXModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GenXModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GrabList> GrabLists
		{
			get
			{
				return this.GetTable<GrabList>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GrabList")]
	public partial class GrabList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _url;
		
		private string _referrer;
		
		private string _status;
		
		private string _priority;
		
		private string _tags;
		
		private System.Nullable<int> _sizeGrabbed;
		
		private System.Nullable<int> _sizeTotal;
		
		private System.Nullable<byte> _retry;
		
		private System.Nullable<System.DateTime> _created;
		
		private System.Nullable<System.DateTime> _lastModified;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OnreferrerChanging(string value);
    partial void OnreferrerChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnpriorityChanging(string value);
    partial void OnpriorityChanged();
    partial void OntagsChanging(string value);
    partial void OntagsChanged();
    partial void OnsizeGrabbedChanging(System.Nullable<int> value);
    partial void OnsizeGrabbedChanged();
    partial void OnsizeTotalChanging(System.Nullable<int> value);
    partial void OnsizeTotalChanged();
    partial void OnretryChanging(System.Nullable<byte> value);
    partial void OnretryChanged();
    partial void OncreatedChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedChanged();
    partial void OnlastModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnlastModifiedChanged();
    #endregion
		
		public GrabList()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NVarChar(255)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referrer", DbType="NVarChar(255)")]
		public string referrer
		{
			get
			{
				return this._referrer;
			}
			set
			{
				if ((this._referrer != value))
				{
					this.OnreferrerChanging(value);
					this.SendPropertyChanging();
					this._referrer = value;
					this.SendPropertyChanged("referrer");
					this.OnreferrerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priority", DbType="NVarChar(10)")]
		public string priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				if ((this._priority != value))
				{
					this.OnpriorityChanging(value);
					this.SendPropertyChanging();
					this._priority = value;
					this.SendPropertyChanged("priority");
					this.OnpriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tags", DbType="NVarChar(MAX)")]
		public string tags
		{
			get
			{
				return this._tags;
			}
			set
			{
				if ((this._tags != value))
				{
					this.OntagsChanging(value);
					this.SendPropertyChanging();
					this._tags = value;
					this.SendPropertyChanged("tags");
					this.OntagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sizeGrabbed", DbType="Int")]
		public System.Nullable<int> sizeGrabbed
		{
			get
			{
				return this._sizeGrabbed;
			}
			set
			{
				if ((this._sizeGrabbed != value))
				{
					this.OnsizeGrabbedChanging(value);
					this.SendPropertyChanging();
					this._sizeGrabbed = value;
					this.SendPropertyChanged("sizeGrabbed");
					this.OnsizeGrabbedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sizeTotal", DbType="Int")]
		public System.Nullable<int> sizeTotal
		{
			get
			{
				return this._sizeTotal;
			}
			set
			{
				if ((this._sizeTotal != value))
				{
					this.OnsizeTotalChanging(value);
					this.SendPropertyChanging();
					this._sizeTotal = value;
					this.SendPropertyChanged("sizeTotal");
					this.OnsizeTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_retry", DbType="TinyInt")]
		public System.Nullable<byte> retry
		{
			get
			{
				return this._retry;
			}
			set
			{
				if ((this._retry != value))
				{
					this.OnretryChanging(value);
					this.SendPropertyChanging();
					this._retry = value;
					this.SendPropertyChanged("retry");
					this.OnretryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> created
		{
			get
			{
				return this._created;
			}
			set
			{
				if ((this._created != value))
				{
					this.OncreatedChanging(value);
					this.SendPropertyChanging();
					this._created = value;
					this.SendPropertyChanged("created");
					this.OncreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastModified", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> lastModified
		{
			get
			{
				return this._lastModified;
			}
			set
			{
				if ((this._lastModified != value))
				{
					this.OnlastModifiedChanging(value);
					this.SendPropertyChanging();
					this._lastModified = value;
					this.SendPropertyChanged("lastModified");
					this.OnlastModifiedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
